name: Get CRAN Stats
on:
  schedule:
    - cron: '0 8 * * 5' # Runs every friday at 8.00
  workflow_dispatch:
jobs:
  cran-stats:
    name: Get CRAN Status

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: execute python script
        run: |
          python python/cran_stats.py
      # Commit changes using the var `should_commit`
      - name: Commit
        continue-on-error: true
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -m 'refreshed CRAN download data'
          git push
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-